# Generated by Django 3.1.4 on 2020-12-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Search',
        ),
    ]
