# Generated by Django 3.1.4 on 2020-12-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201210_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
